name: Ingest Hero Picks
on: { issues: { types: [opened, edited, labeled, reopened] } }
jobs:
  ingest:
    if: contains(join(fromJson(toJson(github.event.issue.labels)).*.name, ','), 'add-picks')
    runs-on: ubuntu-latest
    permissions: { contents: write, issues: write }
    steps:
      - uses: actions/checkout@v4
      - name: Ensure markers
        run: |
          FILE="site/static/heroes.html"
          [ -f "$FILE" ] && grep -q "<!-- AUTO-INSERT:START -->" "$FILE"
      - name: Build block from issue body
        env: { BODY: ${{ github.event.issue.body }} }
        run: |
          echo "$BODY" | tr -d '\r' > body.txt
          {
            echo "<!-- Generated $(date -u +%FT%TZ) -->"
            echo "<ul>"
            while IFS= read -r line; do
              [ -z "$line" ] && continue
              URL="$(echo "$line" | awk -F ' - ' '{print $1}')"
              TITLE="$(echo "$line" | awk -F ' - ' '{print $2}')"
              [ -z "$TITLE" ] && TITLE="$URL"
              echo "  <li><a href=\"$URL\" rel=\"nofollow sponsored\" target=\"_blank\">$TITLE</a></li>"
            done < body.txt
            echo "</ul>"
          } > block.html
      - name: Insert between anchors
        run: |
          awk -v repl="$(sed 's/[&/\]/\\&/g' block.html)" '
            BEGIN{RS=""; ORS=""}
            { if ($0 ~ /<!-- AUTO-INSERT:START -->/ && $0 ~ /<!-- AUTO-INSERT:END -->/)
                sub(/<!-- AUTO-INSERT:START -->.*<!-- AUTO-INSERT:END -->/,
                    "<!-- AUTO-INSERT:START -->\n" repl "\n<!-- AUTO-INSERT:END -->");
              print }' site/static/heroes.html > _tmp && mv _tmp site/static/heroes.html
      - name: Commit + push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add site/static/heroes.html
          git commit -m "Ingest hero picks from issue #${{ github.event.issue.number }}"
          git push
      - name: Comment + close
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          API="${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Content-Type: application/json" \
            -d '{"body":"✅ Hero picks ingested into heroes.html and deployed."}' "$API/comments" >/dev/null
          curl -s -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" -H "Content-Type: application/json" \
            -d '{"state":"closed"}' "$API" >/dev/null
